# Form implementation generated from reading ui file '../task.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Task(object):
    def setupUi(self, Task):
        Task.setObjectName("Task")
        Task.resize(400, 45)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Task)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.taskName = QtWidgets.QLabel(Task)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskName.sizePolicy().hasHeightForWidth())
        self.taskName.setSizePolicy(sizePolicy)
        self.taskName.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.taskName.setObjectName("taskName")
        self.horizontalLayout.addWidget(self.taskName)
        self.delete_2 = QtWidgets.QPushButton(Task)
        self.delete_2.setEnabled(True)
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout.addWidget(self.delete_2)
        self.done = QtWidgets.QPushButton(Task)
        self.done.setObjectName("done")
        self.horizontalLayout.addWidget(self.done)

        self.retranslateUi(Task)
        QtCore.QMetaObject.connectSlotsByName(Task)

    def retranslateUi(self, Task):
        _translate = QtCore.QCoreApplication.translate
        Task.setWindowTitle(_translate("Task", "Form"))
        self.taskName.setText(_translate("Task", "~~task~~"))
        self.delete_2.setText(_translate("Task", "x"))
        self.done.setText(_translate("Task", "v"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Task = QtWidgets.QWidget()
    ui = Ui_Task()
    ui.setupUi(Task)
    Task.show()
    sys.exit(app.exec())
